config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

	#Users
  get 'signup' => 'users#new'
	post 'signup' => 'users#create'
	#Account Settings Just for Email and Password
	get 'account_settings' => 'users#edit'
	patch 'settings' => 'users#update'
	#Login/Logout
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	#Banned Users Redirect
	get 'forbidden' => 'application#forbidden'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'posts#index'
	#Custom RESTful action since there is an "update account settings"
	#And update profile settings
	resources :sessions
	resources :users
	resources :account_activations, only: [:edit]
	resources :comments
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :profiles, only: [:edit, :update, :show] do
		resources :comments, module: :profiles
	end
	resources :posts do
		resources :comments, module: :posts
	end
end

app/views/shared/_flash_messages.html.haml
- if flash[:success].present?
	.row.flash-message
		.col-xs-12
			%p.list-group-item-success{:style=>"text-align:center;padding:10px;"} #{flash[:success]}
- if flash[:notice].present?
	.row.flash-message
		.col-xs-12
			%p.list-group-item-info{:style=>"text-align:center;padding:10px;"} #{flash[:notice]}
- if flash[:error].present?
	.row.flash-message
		.col-xs-12
			%p.list-group-item-danger{:style=>"text-align:center;padding:10px;"} #{flash[:error]}
			- flash[:notice] = flash[:error] = nil

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		.navbar-header
			%button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.navbar-brand{:href => "#"} Discusserly
		#navbar.navbar-collapse.collapse
			%ul.nav.navbar-nav
				%li.active
					=link_to 'Home', root_path
				-if not logged_in?
					-#Not Logged In Links
					%li
						=link_to "Signup", new_user_path
					%li
						=link_to "Log In", login_path
				-if logged_in?
					-# Logged in links
					%li
						=link_to 'Logout', logout_path, method: :delete
					%li
						=link_to 'Account Settings',edit_user_path(@current_user)
					%li
						=link_to 'Edit My Profile', edit_profile_path(@current_user.profile)
					%li
						=link_to 'View My Profile', profile_path(@current_user.profile)
					%li
						=link_to 'Members', users_path