config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

	#Users
  get 'signup' => 'users#new'
	post 'signup' => 'users#create'
	#Account Settings Just for Email and Password
	get 'account_settings' => 'users#edit'
	patch 'settings' => 'users#update'
	#Login/Logout
	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	#Banned Users Redirect
	get 'forbidden' => 'application#forbidden'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'posts#index'
	#Custom RESTful action since there is an "update account settings"
	#And update profile settings
	resources :sessions
	resources :users
	resources :account_activations, only: [:edit]
	resources :comments
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :profiles, only: [:edit, :update, :show] do
		resources :comments, module: :profiles
	end
	resources :posts do
		resources :comments, module: :posts
	end
end

app/models/post.rb
class Post < ApplicationRecord
	include ContentFilter
	belongs_to :user
	has_many :comments, as: :commentable
	default_scope -> { order(created_at: :desc) }
	before_save :check_profanity
	validates :title, presence: true, length: {maximum: 256}
	validates :user_id, presence: true
	validates :content, presence: true, length: {maximum: 1500}

	def check_profanity
		#Profane Words in ContentFilter module
		post_title_arr = self.title.downcase.split(" ")
		post_content_arr = self.content.downcase.split(" ")
		filter = ["*filtered*"]
		post_title_arr.map! { |word| $profane_words.include?(word) ? filter : word}.flatten!
		self.title = post_title_arr.join(" ")
		post_content_arr.map! { | word| $profane_words.include?(word) ? filter : word}.flatten!
		self.content = post_content_arr.join(" " )
	end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable

	private
		
		def set_commentable
			@commentable = Post.find(params[:post_id])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
	before_action :correct_post_owner, only: [:edit, :update, :destroy]
	before_action :check_banned_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
	#Note: In the sessions controller, unconfirmed users will be
	#Automatically redirected to root_url and told to confirm email

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		respond_to do |format|
			if @post.save
				#Redirect to Post
				flash.now[:success] = "Post has been successfully created."
				format.html { redirect_to @post}
				format.json { render :show, status: :created, location: @post }
			else
				format.html {render :new }
				flash[:error] = "Please be sure to add a title and content to your post."
			end
		end
	end

	#Users can only edit/update/destroy a post if that post  belongs to them
	#Or they are administrator
	def edit
		@post = Post.find(params[:id])
	end

	#TODO: Format html on this method
	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			flash.now[:success] = "Post has been successfully updated."
			redirect_to @post
		else
			flash.now[:notice] = "Please fill all required profile fields."
			render 'edit'
		end
	end

	def index
		@posts = Post.all.paginate(page: params[:page])
	end

	def show
		@post = Post.find(params[:id])
		@post_submitted_at = @post.created_at.strftime("%a, %B %d, %Y")
		@users = User.all
		render 'show'
	end

	def destroy
		Post.find(params[:id]).destroy
		flash[:success] = "Post successfully deleted"
		redirect_to posts_url
	end

	private
		
		def post_params
			params.require(:post).permit(:title, :content)
		end

		#Must check and make sure user is logged in AND banned
		def check_banned_user
			if !current_user.nil? && current_user.banned?
				redirect_to forbidden_path
			end
		end
end

app/helpers/posts_helper.rb
module PostsHelper
	
	#Redirects user from edit/update/destroy page unless 
	#They are an admin or post owner
	def correct_post_owner
		@post = Post.find(params[:id])
		unless current_user.admin?
			if current_user.id != @post.user_id
				redirect_to(root_url)
				flash[:error] = "Sorry, you don't have permission to do that."
			end
		end
	end
end

app/views/posts/edit.html.haml
.container
	.row
		.col-md-6
			<center>
			=form_for @post do |f|
				=f.label :title
				=f.text_field :title, :class => "form-control"
				=f.label :content
				=f.text_area :content, :class => "form-control"
				=f.submit "Update Post", :class => "btn btn-primary"
				</center>

app/views/posts/index.html.haml
.container
	.row
		.col-md-2
		.col-md-8
			
			%ul.data-index{:style => "text-align:center"}
				%h1 Welcome to Discusserly! A place for <bold>fun, intelligent and respectful discussion.</bold>
				-if not logged_in?
					=link_to 'Sign Up free to join the discussion', new_user_path
				%h1 Posts
				-if logged_in?
					=link_to 'New Post', new_post_path, :class => 'btn btn-success'
				-@posts.each do |post|
					%li
						.panel.panel-primary{:style => "text-align:center"}
							.panel-heading
								.panel-title
									=link_to post.title, post
							.panel-body
								%h5
									-#by
									-#=post.user.name
								%h5
									Submitted on:
									=post.created_at.strftime("%a, %B %d, %Y")
								
								-#Preview of text
								%p
									=post.content.html_safe[0, 200] + "..."
								<center>
								=link_to 'Read More...', post_path(post), :class => 'btn btn-primary'
								%br
								-if logged_in? && current_user.admin?
									-#Admin Users Will See Edit and Delete Options for All Posts
									=link_to 'Edit', edit_post_path(post), :class => 'btn btn-warning'
									=link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you wish to delete this post? This cannot  be undone'}, :class => 'btn btn-danger'
								-elsif logged_in? && post.user_id == current_user.id
									-#Users can only see Edit and Delete Options for their Own Posts
									=link_to 'Edit', edit_post_path(post), :class => 'btn btn-warning'
									=link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you wish to delete this post? This cannot be undone'}, :class => 'btn btn-danger'
								</center>
				=will_paginate	
		.col-md-2

app/views/posts/new.html.haml
.container
	.row
		.col-md-6
			<center>
			=form_for @post do |f|
				=f.label :title
				=f.text_field :title, :class => "form-control"
				=f.label :content
				=f.text_area :content, :class => "form-control", :style => "width:500px"
				=f.submit "Create Post", :class => "btn btn-primary"
			</center>

app/views/posts/show.html.haml
.container
	.row
		.col-md-6
			.panel.panel-primary{:style => 'text-align:center'}
				.panel-heading
					.panel-title
						=@post.title
				.panel-body
					%h5
						by
						=@post.user.name
					%p
						Submitted on:
						=@post_submitted_at
					%h6
						=@post.content.html_safe
					-if logged_in? && @post.user_id == current_user.id
						=link_to 'Edit', edit_post_path(@post), :class => 'btn btn-warning'
						=link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure you wish to delete this post? This cannot be undone.'}, :class => 'btn  btn-danger'
		.col-md-6
			.panel.panel-primary{:style => 'text-align:center'}
				.panel-heding
					.panel-title
						%h5 Comments
				.panel-body
					= render partial: 'comments/comments', locals: {commentable: @post}
					-if logged_in?
						= render partial: 'comments/comment_form', locals: {commentable: @post}
							